drop table lf_airui_pro.xwb;
create table lf_airui_pro.xwb as
select device_number,parse_url(case when url like 'http://%' then url else concat('http://',url) end,'HOST') as url_host
from lf_airui_pro.base_origin_log_ext where pt_days='20190520' and prov_id = '051';

select bmd,count(1) from ( 
select 
case 
when url_host= 'a0.pstatp.com' then 'a0.pstatp.com'
when url_host= 'a1.pstatp.com' then 'a1.pstatp.com'
when url_host= 'a3.pstatp.com' then 'a3.pstatp.com'
when url_host= 'a6.pstatp.com' then 'a6.pstatp.com'
when url_host= 'wd3.pstatp.com' then 'wd3.pstatp.com'
when url_host= 'wd1.pstatp.com' then 'wd1.pstatp.com'
when url_host= 'wd2.pstatp.com' then 'wd2.pstatp.com'
when url_host= 'developer.toutiao.com' then 'developer.toutiao.com'
when url_host= 'news.ssp.qq.com' then 'news.ssp.qq.com'
when url_host= 'op.ssp.qq.com' then 'op.ssp.qq.com'
when url_host= 'pnewsapp.tc.qq.com' then 'pnewsapp.tc.qq.com'
when url_host= 'r.inews.qq.com' then 'r.inews.qq.com'
when url_host= 'rpt.gdt.qq.com' then 'rpt.gdt.qq.com'
when url_host= 'up.inews.qq.com' then 'up.inews.qq.com'
when url_host= 'w.inews.qq.com' then 'w.inews.qq.com'
when url_host= 'wap.mpush.qq.com' then 'wap.mpush.qq.com'
when url_host= 'wise.qq.com' then 'wise.qq.com'
when url_host= 'cnews.wap.mpush.qq.com' then 'cnews.wap.mpush.qq.com'
when url_host= 'kuaibao.qq.com' then 'kuaibao.qq.com'
when url_host= 'r.cnews.qq.com' then 'r.cnews.qq.com'
when url_host= 'p.ssp.qq.com' then 'p.ssp.qq.com'
when url_host= 'lives.l.qq.com' then 'lives.l.qq.com'
when url_host= 'w.cnews.qq.com' then 'w.cnews.qq.com'
when url_host= 'm.analytics.126.net' then 'm.analytics.126.net'
when url_host= 'c.m.163.com' then 'c.m.163.com'
when url_host= 'comment.api.163.com' then 'comment.api.163.com'
when url_host= 'comment.news.163.com' then 'comment.news.163.com'
when url_host= 'nex.163.com' then 'nex.163.com'
when url_host= 'v.monitor.ws.netease.com' then 'v.monitor.ws.netease.com'
when url_host= 'api.3g.ifeng.com' then 'api.3g.ifeng.com'
when url_host= 'api.iclient.ifeng.com' then 'api.iclient.ifeng.com'
when url_host= 'ips.ifeng.com' then 'ips.ifeng.com'
when url_host= 'stadig.ifeng.com' then 'stadig.ifeng.com'
when url_host= 'stadig0.ifeng.com' then 'stadig0.ifeng.com'
when url_host= 'user.iclient.ifeng.com' then 'user.iclient.ifeng.com'
when url_host= 'video19.ifeng.com' then 'video19.ifeng.com'
when url_host= 'c0.ifengimg.com' then 'c0.ifengimg.com'
when url_host= 'c1.ifengimg.com' then 'c1.ifengimg.com'
when url_host= 'c2.ifengimg.com' then 'c2.ifengimg.com'
when url_host= 'c3.ifengimg.com' then 'c3.ifengimg.com'
when url_host= 'd.ifengimg.com' then 'd.ifengimg.com'
when url_host= 'api.k.sohu.com' then 'api.k.sohu.com'
when url_host= 'pic.k.sohu.com' then 'pic.k.sohu.com'
when url_host= 't.ads.sohu.com' then 't.ads.sohu.com'
when url_host= 'zcache.k.sohu.com' then 'zcache.k.sohu.com'
when url_host= 'newsapi.sina.cn' then 'newsapi.sina.cn'
when url_host= 'beacon.sina.com.cn' then 'beacon.sina.com.cn'
when url_host= 'l.sinaimg.cn' then 'l.sinaimg.cn'
when url_host= 'hmma.baidu.com' then 'hmma.baidu.com'
when url_host= 'boxnovel.baidu.com' then 'boxnovel.baidu.com'
when url_host= 'ext.baidu.com' then 'ext.baidu.com'
when url_host= 'f10.baidu.com' then 'f10.baidu.com'
when url_host= 'f11.baidu.com' then 'f11.baidu.com'
when url_host= 'f12.baidu.com' then 'f12.baidu.com'
when url_host= 'feed.baidu.com' then 'feed.baidu.com'
when url_host= 'mbd.baidu.com' then 'mbd.baidu.com'
when url_host= 'sp0.baidu.com' then 'sp0.baidu.com'
when url_host= 'sp1.baidu.com' then 'sp1.baidu.com'
when url_host= 'sp2.baidu.com' then 'sp2.baidu.com'
when url_host= 'sp3.baidu.com' then 'sp3.baidu.com'
when url_host= 'voice.baidu.com' then 'voice.baidu.com'
when url_host= '2019static.bdstatic.com' then '2019static.bdstatic.com'
when url_host= 'vd1.bdstatic.com' then 'vd1.bdstatic.com'
when url_host= 'vd2.bdstatic.com' then 'vd2.bdstatic.com'
when url_host= 'vd3.bdstatic.com' then 'vd3.bdstatic.com'
when url_host= 'vd4.bdstatic.com' then 'vd4.bdstatic.com'
when url_host= 'vdse.bdstatic.com' then 'vdse.bdstatic.com'
when url_host= 'wmedia-track.uc.cn' then 'wmedia-track.uc.cn'
when url_host= 'm.uczzd.cn' then 'm.uczzd.cn'
when url_host= 'api.c.uc.cn' then 'api.c.uc.cn'
when url_host= 'api.mp.uc.cn' then 'api.mp.uc.cn'
when url_host= 'bigsubs.zc.uae.uc.cn' then 'bigsubs.zc.uae.uc.cn'
when url_host= 'img.v.uc.cn' then 'img.v.uc.cn'
when url_host= 'navi-user.uc.cn' then 'navi-user.uc.cn'
when url_host= 'track.uc.cn' then 'track.uc.cn'
when url_host= 'iflow.uczzd.cn' then 'iflow.uczzd.cn'
when url_host= 'image.uczzd.cn' then 'image.uczzd.cn'
when url_host= 'api.amemv.com' then 'api.amemv.com'
when url_host= 'aweme.snssdk.com' then 'aweme.snssdk.com'
when url_host= 'aweme-bee.snssdk.com' then 'aweme-bee.snssdk.com'
when url_host= 'aweme-bee-hl.snssdk.com' then 'aweme-bee-hl.snssdk.com'
when url_host= 'aweme-c.snssdk.com' then 'aweme-c.snssdk.com'
when url_host= 'aweme-cold.snssdk.com' then 'aweme-cold.snssdk.com'
when url_host= 'aweme-eagle.snssdk.com' then 'aweme-eagle.snssdk.com'
when url_host= 'aweme-hl.snssdk.com' then 'aweme-hl.snssdk.com'
when url_host= 'aweme-n.snssdk.com' then 'aweme-n.snssdk.com'
when url_host= 'aweme-o.snssdk.com' then 'aweme-o.snssdk.com'
when url_host= 'aweme-swan.snssdk.com' then 'aweme-swan.snssdk.com'
when url_host= 'aweme-swan-hl.snssdk.com' then 'aweme-swan-hl.snssdk.com'
when url_host= 'aweme-yak.snssdk.com' then 'aweme-yak.snssdk.com'
when url_host= 'aweme-yak-hl.snssdk.com' then 'aweme-yak-hl.snssdk.com'
when url_host= 'effect.snssdk.com' then 'effect.snssdk.com'
when url_host= 'yoo.qpic.cn' then 'yoo.qpic.cn'
when url_host= 'api.huoshan.com' then 'api.huoshan.com'
when url_host= 'y.gtimg.cn' then 'y.gtimg.cn'
when url_host= 'monitor.music.qq.com' then 'monitor.music.qq.com'
when url_host= 'p.l.qq.com' then 'p.l.qq.com'
when url_host= 'stat.3g.music.qq.com' then 'stat.3g.music.qq.com'
when url_host= 'y.qq.com' then 'y.qq.com'
when url_host= 'apm.music.163.com' then 'apm.music.163.com'
when url_host= 'clientlog.music.163.com' then 'clientlog.music.163.com'
when url_host= 'interface.music.163.com' then 'interface.music.163.com'
when url_host= 'music.163.com' then 'music.163.com'
when url_host= 'freepay.xmcdn.com' then 'freepay.xmcdn.com'
when url_host= 'api.weibo.cn' then 'api.weibo.cn'
when url_host= 'mfbizweb.19ego.cn' then 'mfbizweb.19ego.cn'
when url_host= 'api.mgzf.com' then 'api.mgzf.com'
when url_host= 'assets.mgzf.com' then 'assets.mgzf.com'
when url_host= 'ali.enmonster.com' then 'ali.enmonster.com'
when url_host= 'vrs.enmonster.com' then 'vrs.enmonster.com'
when url_host= 'loggw.alipay.com' then 'loggw.alipay.com'
when url_host= 'mdap.alipay.com' then 'mdap.alipay.com'
when url_host= 'mcgw.alipay.com' then 'mcgw.alipay.com'
when url_host= 'mobilegw.alipay.com' then 'mobilegw.alipay.com'
when url_host= 'h5.ele.me' then 'h5.ele.me'
when url_host= 'pages.tmall.com' then 'pages.tmall.com'
when url_host= 'guide-acs.m.taobao.com' then 'guide-acs.m.taobao.com'
when url_host= 'wgo.mmstat.com' then 'wgo.mmstat.com'
when url_host= 'log.mmstat.com' then 'log.mmstat.com'
when url_host= 'h5.vip.youku.com' then 'h5.vip.youku.com'
when url_host= 'campus.alipay-eco.com' then 'campus.alipay-eco.com'
when url_host= 'mycar-vbizplatform.alipay-eco.com' then 'mycar-vbizplatform.alipay-eco.com'
when url_host= 'mps.amap.com' then 'mps.amap.com'
when url_host= 'open.antfortune.com' then 'open.antfortune.com'
when url_host= 'render.alipay.com' then 'render.alipay.com'
when url_host= 'tfsimg.alipay.com' then 'tfsimg.alipay.com'
when url_host= 'mtop.damai.cn' then 'mtop.damai.cn'
when url_host= 'csmobile.alipay.com' then 'csmobile.alipay.com'
when url_host= 'apis.didapinche.com' then 'apis.didapinche.com'
when url_host= 'fragment.tmall.com' then 'fragment.tmall.com'
when url_host= 's.click.tmall.com' then 's.click.tmall.com'
when url_host= 's.click.taobao.com' then 's.click.taobao.com'
when url_host= 'miniappweb.shuqireader.com' then 'miniappweb.shuqireader.com'
when url_host= 'app.woaizuji.com' then 'app.woaizuji.com'
when url_host= 'cbp.alipay-eco.com' then 'cbp.alipay-eco.com'
when url_host= 'ubt.hellobike.com' then 'ubt.hellobike.com'
when url_host= 'api.hellobike.com' then 'api.hellobike.com'
when url_host= 'huaka.cmicrwx.cn' then 'huaka.cmicrwx.cn'
when url_host= 'rent.tubadianzi.com' then 'rent.tubadianzi.com'
when url_host= 'mobile.12306.cn' then 'mobile.12306.cn'
when url_host='microapp.bytedance.com' then 'microapp.bytedance.com'
when url_host='yebprod.alipay.com' then 'yebprod.alipay.com'
when url_host='zm.zmxy.com' then 'zm.zmxy.com'
when url_host='zm.zmxy.com.cn' then 'zm.zmxy.com.cn'
when url_host='csmobile.alipay.com' then 'csmobile.alipay.com'
when url_host='bxcloudstore.alicdn.com' then 'bxcloudstore.alicdn.com'
when url_host='dtliving.alicdn.com' then 'dtliving.alicdn.com'
when url_host='vote.dingteam.com' then 'vote.dingteam.com'
when url_host='club.dingding.xin' then 'club.dingding.xin'
when url_host='video.ums.uc.cn' then 'video.ums.uc.cn'
when url_host='so.m.sm.cn' then 'so.m.sm.cn'
when url_host='sugs.m.sm.cn' then 'sugs.m.sm.cn'
when url_host='xm.sm.cn' then 'xm.sm.cn'
when url_host='smartprogram.baidu.com' then 'smartprogram.baidu.com'
when url_host='bdbus-turbonet.com' then 'bdbus-turbonet.com'
when  instr(url_host,'.snssdk.com')>0  then '*.snssdk.com'
when  instr(url_host,'.shuqireader.com')>0  then 'shuqireader.com'
when  instr(url_host,'.kugou.com')>0  then 'kugou.com'
when  instr(url_host,'.koowo.com')>0  then 'koowo.com'
when  instr(url_host,'.kuwo.cn')>0  then 'kuwo.cn'
when  instr(url_host,'.ximalaya.com')>0  then 'ximalaya.com'
when  instr(url_host,'.dingtalk.com')>0  then '*.dingtalk.com'
when  instr(url_host,'.antfortune.com')>0  then '*.antfortune.com'
 end as bmd,device_number from lf_airui_pro.xwb                                                                               
)a
group by bmd;




