
select    '支付宝各模块统计' model,
          '日期' pt_days,
          'uv_支付宝登陆' uv_1,
          'uv_支付宝财富模块' uv0,
          'uv_支付宝使用mdap' uv1,
          'uv_支付宝使用mcgw' uv2,
          'uv_支付宝使用mobilegw' uv3,
          'uv_支付宝-移动特权' uv4,
          'uv_支付宝-蘑菇租房' uv5,
          'uv_支付宝-怪兽充电' uv6,
          'uv_支付宝-哈喽单车' uv7,
          'uv_支付宝-饿了么入口' uv8,
          'uv_支付宝-天猫小程序入口' uv9,
          'uv_支付宝-优酷会员' uv10,
          'uv_支付宝-校园生活' uv11,
          'uv_支付宝-车主服务' uv12,
          'uv_支付宝-高德' uv13,
          'uv_支付宝-大麦网' uv14,
          'uv_支付宝-嘀嗒出行' uv15,
          'uv_支付宝-每日必抢/聚划算' uv16,
          'uv_支付宝-天猫商品点击' uv17,
          'uv_支付宝-淘宝商品点击' uv18,
          'uv_芝麻信用' uv19,
          'uv_支付宝-财富号' uv21,
          'uv_汽车报价' uv22,
          'uv_高德实时公交' uv23,
          'uv_寻证易' uv24,
          'uv_萌宠到家' uv25,
          'uv_移动花卡' uv26,
          'uv_社保查询' uv27,
          'uv_书旗小说' uv28,
          'uv_肯德基+' uv29,
          'uv_国家移民局' uv31,
          'uv_爱租机' uv32,
          'uv_哈罗出行' uv33,
          'uv_12306出行' uv34,
          'uv_麦当劳' uv35,
          'uv_交管12123' uv36,
          'uv_哇哈哈到家' uv37,
          'uv_ofo小黄车' uv38,
          'uv_股票财富号' uv40,
          'uv_adv财富号' uv41,
          'uv_私募财富号' uv42,
          'uv_天弘基金' uv43,
          'uv_render财富' uv44,
          'uv_支付宝小程序' uv45,
          'uv_最美证件照' uv46,
          'uv_全国社保计算器' uv47,
          'uv_工资个税计算器' uv48,
          'uv_浙江预约挂号' uv49,
          'uv_药急送' uv50,
          'uv_免费照片打印' uv51,
          'uv_人人租机' uv52,
          'uv_内啥' uv53,
          'uv_公立医院体检预约' uv54,
          'uv_齐天大圣' uv55,
          'uv_旧衣服回收' uv56,
          'uv_违章缴费' uv57,
          'uv_政府业务' uv58,
          'uv_魔盒citybox' uv59,
          'uv_衣二三' uv60,
          'uv_微车' uv61,
          'uv_优酷会员兑换' uv62,
          'uv_支付宝-客服' uv63,
          'uv_蚂蚁保险' uv64,
          'uv_余额宝' uv65,                
          'uv_支付宝登陆' pv_1,
          'pv_支付宝财富模块' pv0,
          'pv_支付宝使用mdap' pv1,
          'pv_支付宝使用mcgw' pv2,
          'pv_支付宝使用mobilegw' pv3,
          'pv_支付宝-移动特权' pv4,
          'pv_支付宝-蘑菇租房' pv5,
          'pv_支付宝-怪兽充电' pv6,
          'pv_支付宝-哈喽单车' pv7,
          'pv_支付宝-饿了么入口' pv8,
          'pv_支付宝-天猫小程序入口' pv9,
          'pv_支付宝-优酷会员' pv10,
          'pv_支付宝-校园生活' pv11,
          'pv_支付宝-车主服务' pv12,
          'pv_支付宝-高德' pv13,
          'pv_支付宝-大麦网' pv14,
          'pv_支付宝-嘀嗒出行' pv15,
          'pv_支付宝-每日必抢/聚划算' pv16,
          'pv_支付宝-天猫商品点击' pv17,
          'pv_支付宝-淘宝商品点击' pv18,
          'pv_芝麻信用' pv19,
          'pv_支付宝-财富号' pv21,
          'pv_汽车报价' pv22,
          'pv_高德实时公交' pv23,
          'pv_寻证易' pv24,
          'pv_萌宠到家' pv25,
          'pv_移动花卡' pv26,
          'pv_社保查询' pv27,
          'pv_书旗小说' pv28,
          'pv_肯德基+' pv29,
          'pv_国家移民局' pv31,
          'pv_爱租机' pv32,
          'pv_哈罗出行' pv33,
          'pv_12306出行' pv34,
          'pv_麦当劳' pv35,
          'pv_交管12123' pv36,
          'pv_哇哈哈到家' pv37,
          'pv_ofo小黄车' pv38,
          'pv_股票财富号' pv40,
          'pv_adv财富号' pv41,
          'pv_私募财富号' pv42,
          'pv_天弘基金' pv43,
          'pv_render财富' pv44,
          'pv_支付宝小程序' pv45,
          'pv_最美证件照' pv46,
          'pv_全国社保计算器' pv47,
          'pv_工资个税计算器' pv48,
          'pv_浙江预约挂号' pv49,
          'pv_药急送' pv50,
          'pv_免费照片打印' pv51,
          'pv_人人租机' pv52,
          'pv_内啥' pv53,
          'pv_公立医院体检预约' pv54,
          'pv_齐天大圣' pv55,
          'pv_旧衣服回收' pv56,
          'pv_违章缴费' pv57,
          'pv_政府业务' pv58,
          'pv_魔盒citybox' pv59,
          'pv_衣二三' pv60,
          'pv_微车' pv61,
          'pv_优酷会员兑换' pv62,
          'pv_支付宝-客服' pv63,
          'pv_蚂蚁保险' pv64,
          'pv_余额宝' pv65
union all
select  '支付宝各模块统计' model,
        pt_days,
        count(distinct(case when tag_login=1 then device_number else null end)) uv_1,
        count(distinct(case when tag_cf=1 then device_number else null end)) uv0,
        count(distinct(case when tag1=1 then device_number else null end)) uv1,
        count(distinct(case when tag2=1 then device_number else null end)) uv2,
        count(distinct(case when tag3=1 then device_number else null end)) uv3,
        count(distinct(case when tag4=1  and tag_login=1 then device_number else null end)) uv4,
        count(distinct(case when tag5=1  and tag_login=1 then device_number else null end)) uv5,
        count(distinct(case when tag6=1  and tag_login=1 then device_number else null end)) uv6,
        count(distinct(case when tag7=1  and tag_login=1 then device_number else null end)) uv7,
        count(distinct(case when tag8=1  and tag_login=1 then device_number else null end)) uv8,
        count(distinct(case when tag9=1  and tag_login=1 then device_number else null end)) uv9,
        count(distinct(case when tag10=1  and tag_login=1 then device_number else null end)) uv10,
        count(distinct(case when tag11=1  and tag_login=1 then device_number else null end)) uv11,
        count(distinct(case when tag12=1  and tag_login=1 then device_number else null end)) uv12,
        count(distinct(case when tag13=1  and tag_login=1 then device_number else null end)) uv13,
        count(distinct(case when tag14=1  and tag_login=1 then device_number else null end)) uv14,
        count(distinct(case when tag15=1  and tag_login=1 then device_number else null end)) uv15,
        count(distinct(case when tag16=1  and tag_login=1 then device_number else null end)) uv16,
        count(distinct(case when tag17=1  and tag_login=1 then device_number else null end)) uv17,
        count(distinct(case when tag18=1  and tag_login=1 then device_number else null end)) uv18,
        count(distinct(case when tag19=1  and tag_login=1 then device_number else null end)) uv19,
        count(distinct(case when tag21=1  and tag_login=1 then device_number else null end)) uv21,
        count(distinct(case when tag22=1  and tag_login=1 then device_number else null end)) uv22,
        count(distinct(case when tag23=1  and tag_login=1 then device_number else null end)) uv23,
        count(distinct(case when tag24=1  and tag_login=1 then device_number else null end)) uv24,
        count(distinct(case when tag25=1  and tag_login=1 then device_number else null end)) uv25,
        count(distinct(case when tag26=1  and tag_login=1 then device_number else null end)) uv26,
        count(distinct(case when tag27=1  and tag_login=1 then device_number else null end)) uv27,
        count(distinct(case when tag28=1  and tag_login=1 then device_number else null end)) uv28,
        count(distinct(case when tag29=1  and tag_login=1 then device_number else null end)) uv29,
        count(distinct(case when tag31=1  and tag_login=1 then device_number else null end)) uv31,
        count(distinct(case when tag32=1  and tag_login=1 then device_number else null end)) uv32,
        count(distinct(case when tag33=1  and tag_login=1 then device_number else null end)) uv33,
        count(distinct(case when tag34=1  and tag_login=1 then device_number else null end)) uv34,
        count(distinct(case when tag35=1  and tag_login=1 then device_number else null end)) uv35,
        count(distinct(case when tag36=1  and tag_login=1 then device_number else null end)) uv36,
        count(distinct(case when tag37=1  and tag_login=1 then device_number else null end)) uv37,
        count(distinct(case when tag38=1  and tag_login=1 then device_number else null end)) uv38,
        count(distinct(case when tag40=1  and tag_login=1 then device_number else null end)) uv40,
        count(distinct(case when tag41=1  and tag_login=1 then device_number else null end)) uv41,
        count(distinct(case when tag42=1  and tag_login=1 then device_number else null end)) uv42,
        count(distinct(case when tag43=1  and tag_login=1 then device_number else null end)) uv43,
        count(distinct(case when tag44=1  and tag_login=1 then device_number else null end)) uv44,
        count(distinct(case when tag45=1  and tag_login=1 then device_number else null end)) uv45,
        count(distinct(case when tag46=1  and tag_login=1 then device_number else null end)) uv46,
        count(distinct(case when tag47=1  and tag_login=1 then device_number else null end)) uv47,
        count(distinct(case when tag48=1  and tag_login=1 then device_number else null end)) uv48,
        count(distinct(case when tag49=1  and tag_login=1 then device_number else null end)) uv49,
        count(distinct(case when tag50=1  and tag_login=1 then device_number else null end)) uv50,
        count(distinct(case when tag51=1  and tag_login=1 then device_number else null end)) uv51,
        count(distinct(case when tag52=1  and tag_login=1 then device_number else null end)) uv52,
        count(distinct(case when tag53=1  and tag_login=1 then device_number else null end)) uv53,
        count(distinct(case when tag54=1  and tag_login=1 then device_number else null end)) uv54,
        count(distinct(case when tag55=1  and tag_login=1 then device_number else null end)) uv55,
        count(distinct(case when tag56=1  and tag_login=1 then device_number else null end)) uv56,
        count(distinct(case when tag57=1  and tag_login=1 then device_number else null end)) uv57,
        count(distinct(case when tag58=1  and tag_login=1 then device_number else null end)) uv58,
        count(distinct(case when tag59=1  and tag_login=1 then device_number else null end)) uv59,
        count(distinct(case when tag60=1  and tag_login=1 then device_number else null end)) uv60,
        count(distinct(case when tag61=1  and tag_login=1 then device_number else null end)) uv61,
        count(distinct(case when tag62=1  and tag_login=1 then device_number else null end)) uv62,
        count(distinct(case when tag63=1 then device_number else null end)) uv63,
        count(distinct(case when tag64=1 then device_number else null end)) uv64,
        count(distinct(case when tag65=1 then device_number else null end)) uv65,
        sum(case when tag_login=1 then 1 else 0 end) pv_1,
        sum(case when tag_cf=1 then 1 else 0 end) pv0,
        sum(case when tag1=1 then 1 else 0 end) pv1,
        sum(case when tag2=1 then 1 else 0 end) pv2,
        sum(case when tag3=1 then 1 else 0 end) pv3,
        sum(case when tag4=1  and tag_login=1 then 1 else 0 end) pv4,
        sum(case when tag5=1  and tag_login=1 then 1 else 0 end) pv5,
        sum(case when tag6=1  and tag_login=1 then 1 else 0 end) pv6,
        sum(case when tag7=1  and tag_login=1 then 1 else 0 end) pv7,
        sum(case when tag8=1  and tag_login=1 then 1 else 0 end) pv8,
        sum(case when tag9=1  and tag_login=1 then 1 else 0 end) pv9,
        sum(case when tag10=1  and tag_login=1 then 1 else 0 end) pv10,
        sum(case when tag11=1  and tag_login=1 then 1 else 0 end) pv11,
        sum(case when tag12=1  and tag_login=1 then 1 else 0 end) pv12,
        sum(case when tag13=1  and tag_login=1 then 1 else 0 end) pv13,
        sum(case when tag14=1  and tag_login=1 then 1 else 0 end) pv14,
        sum(case when tag15=1  and tag_login=1 then 1 else 0 end) pv15,
        sum(case when tag16=1  and tag_login=1 then 1 else 0 end) pv16,
        sum(case when tag17=1  and tag_login=1 then 1 else 0 end) pv17,
        sum(case when tag18=1  and tag_login=1 then 1 else 0 end) pv18,
        sum(case when tag19=1  and tag_login=1 then 1 else 0 end) pv19,
        sum(case when tag21=1  and tag_login=1 then 1 else 0 end) pv21,
        sum(case when tag22=1  and tag_login=1 then 1 else 0 end) pv22,
        sum(case when tag23=1  and tag_login=1 then 1 else 0 end) pv23,
        sum(case when tag24=1  and tag_login=1 then 1 else 0 end) pv24,
        sum(case when tag25=1  and tag_login=1 then 1 else 0 end) pv25,
        sum(case when tag26=1  and tag_login=1 then 1 else 0 end) pv26,
        sum(case when tag27=1  and tag_login=1 then 1 else 0 end) pv27,
        sum(case when tag28=1  and tag_login=1 then 1 else 0 end) pv28,
        sum(case when tag29=1  and tag_login=1 then 1 else 0 end) pv29,
        sum(case when tag31=1  and tag_login=1 then 1 else 0 end) pv31,
        sum(case when tag32=1  and tag_login=1 then 1 else 0 end) pv32,
        sum(case when tag33=1  and tag_login=1 then 1 else 0 end) pv33,
        sum(case when tag34=1  and tag_login=1 then 1 else 0 end) pv34,
        sum(case when tag35=1  and tag_login=1 then 1 else 0 end) pv35,
        sum(case when tag36=1  and tag_login=1 then 1 else 0 end) pv36,
        sum(case when tag37=1  and tag_login=1 then 1 else 0 end) pv37,
        sum(case when tag38=1  and tag_login=1 then 1 else 0 end) pv38,
        sum(case when tag40=1  and tag_login=1 then 1 else 0 end) pv40,
        sum(case when tag41=1  and tag_login=1 then 1 else 0 end) pv41,
        sum(case when tag42=1  and tag_login=1 then 1 else 0 end) pv42,
        sum(case when tag43=1  and tag_login=1 then 1 else 0 end) pv43,
        sum(case when tag44=1  and tag_login=1 then 1 else 0 end) pv44,
        sum(case when tag45=1  and tag_login=1 then 1 else 0 end) pv45,
        sum(case when tag46=1  and tag_login=1 then 1 else 0 end) pv46,
        sum(case when tag47=1  and tag_login=1 then 1 else 0 end) pv47,
        sum(case when tag48=1  and tag_login=1 then 1 else 0 end) pv48,
        sum(case when tag49=1  and tag_login=1 then 1 else 0 end) pv49,
        sum(case when tag50=1  and tag_login=1 then 1 else 0 end) pv50,
        sum(case when tag51=1  and tag_login=1 then 1 else 0 end) pv51,
        sum(case when tag52=1  and tag_login=1 then 1 else 0 end) pv52,
        sum(case when tag53=1  and tag_login=1 then 1 else 0 end) pv53,
        sum(case when tag54=1  and tag_login=1 then 1 else 0 end) pv54,
        sum(case when tag55=1  and tag_login=1 then 1 else 0 end) pv55,
        sum(case when tag56=1  and tag_login=1 then 1 else 0 end) pv56,
        sum(case when tag57=1  and tag_login=1 then 1 else 0 end) pv57,
        sum(case when tag58=1  and tag_login=1 then 1 else 0 end) pv58,
        sum(case when tag59=1  and tag_login=1 then 1 else 0 end) pv59,
        sum(case when tag60=1  and tag_login=1 then 1 else 0 end) pv60,
        sum(case when tag61=1  and tag_login=1 then 1 else 0 end) pv61,
        sum(case when tag62=1  and tag_login=1 then 1 else 0 end) pv62,
        sum(case when tag63=1 then 1 else 0 end) pv63,
        sum(case when tag64=1 then 1 else 0 end) pv64,
        sum(case when tag65=1 then 1 else 0 end) pv65
    from ( select pt_days,
                  device_number,
                  hh,
                  max(case when instr(url_host,'antfortune.com')>0 then 1 else 0 end) tag_cf,
                  max(case when url_host='loggw.alipay.com' then 1 else 0 end) tag_login,
                  max(case when url_host='mdap.alipay.com' then 1 else 0 end) tag1,
                  max(case when url_host='mcgw.alipay.com' then 1 else 0 end) tag2,
                  max(case when url_host='mobilegw.alipay.com' then 1 else 0 end) tag3,
                  max(case when url_host='mfbizweb.19ego.cn' then 1 else 0 end) tag4,
                  max(case when url_host='api.mgzf.com' then 1 else 0 end) tag5,
                  max(case when url_host='ali.enmonster.com' then 1 else 0 end) tag6,
                  max(case when url_host='api.hellobike.com' then 1 else 0 end) tag7,
                  max(case when url_host='h5.ele.me' then 1 else 0 end) tag8,
                  max(case when url_host='pages.tmall.com' then 1 else 0 end) tag9,
                  max(case when url_host='h5.vip.youku.com' then 1 else 0 end) tag10,
                  max(case when url_host='campus.alipay-eco.com' then 1 else 0 end) tag11,
                  max(case when url_host='mycar-vbizplatform.alipay-eco.com' then 1 else 0 end) tag12,
                  max(case when url_host='mps.amap.com' then 1 else 0 end) tag13,
                  max(case when url_host='mtop.damai.cn' then 1 else 0 end) tag14,
                  max(case when url_host='apis.didapinche.com' then 1 else 0 end) tag15,
                  max(case when url_host='fragment.tmall.com' then 1 else 0 end) tag16,
                  max(case when url_host='s.click.tmall.com' then 1 else 0 end) tag17,
                  max(case when url_host='s.click.taobao.com' then 1 else 0 end) tag18,
                  max(case when instr(url_host,'zmxy.com')>0 then 1 else 0 end) tag19,
                  max(case when url_host='fundcaifuhao.antfortune.com' then 1 else 0 end) tag21,
                  max(case when url_host='magear.pangku.com' then 1 else 0 end) tag22,
                  max(case when url_host='aisle.amap.com' then 1 else 0 end) tag23,
                  max(case when url_host='easysearchcard.chuxingyouhui.com' then 1 else 0 end) tag24,
                  max(case when url_host='mcdj.qipinke.com' then 1 else 0 end) tag25,
                  max(case when url_host='huaka.cmicrwx.cn' then 1 else 0 end) tag26,
                  max(case when url_host='cbp.alipay-eco.com' then 1 else 0 end) tag27,
                  max(case when url_host='miniappweb.shuqireader.com' then 1 else 0 end) tag28,
                  max(case when url_host in ('orders.kfc.com.cn','imgorder.kfc.com.cn') then 1 else 0 end) tag29,
                  max(case when url_host='niaprod.alipay-eco.com' then 1 else 0 end) tag31,
                  max(case when url_host='app.woaizuji.com' then 1 else 0 end) tag32,
                  max(case when url_host='ubt.hellobike.com' then 1 else 0 end) tag33,
                  max(case when url_host='crnetzsjk.crnet.info' then 1 else 0 end) tag34,
                  max(case when url_host='imcd.jaxcx.com' then 1 else 0 end) tag35,
                  max(case when url_host='goveco.alipay.com' then 1 else 0 end) tag36,
                  max(case when url_host='www.mywhh.com' then 1 else 0 end) tag37,
                  max(case when url_host='scofo.ofo.so' then 1 else 0 end) tag38,
                  max(case when url_host='stockcaifuhao.antfortune.com' then 1 else 0 end) tag40,
                  max(case when url_host='advcaifuhao.antfortune.com' then 1 else 0 end) tag41,
                  max(case when url_host='pecaifuhao.antfortune.com' then 1 else 0 end) tag42,
                  max(case when url_host='cfh.tianhongjijin.com.cn' then 1 else 0 end) tag43,
                  max(case when url_host='render.antfortune.com' then 1 else 0 end) tag44,
                  max(case when url_host='mini.open.alipay.com' then 1 else 0 end) tag45,
                  max(case when url_host='apicall.id-photo-verify.com' then 1 else 0 end) tag46,
                  max(case when url_host='scalc-min.renliwo.com' then 1 else 0 end) tag47,
                  max(case when url_host='taxcal.renliwo.com' then 1 else 0 end) tag48,
                  max(case when url_host='ghws5.zj12580.cn' then 1 else 0 end) tag49,
                  max(case when url_host='api.zp315.cn' then 1 else 0 end) tag50,
                  max(case when url_host='api.songzhaopian.com' then 1 else 0 end) tag51,
                  max(case when url_host='m.rrzuji.com' then 1 else 0 end) tag52,
                  max(case when url_host='www.neisha.cc' then 1 else 0 end) tag53,
                  max(case when url_host='xcx.etong-online.com' then 1 else 0 end) tag54,
                  max(case when url_host='mys4s.cn' then 1 else 0 end) tag55,
                  max(case when url_host='lmf.gzluowang.com' then 1 else 0 end) tag56,
                  max(case when url_host='appgw.cmp520.com' then 1 else 0 end) tag57,
                  max(case when url_host='goveco.alipay.com' then 1 else 0 end) tag58,
                  max(case when url_host='cityboxapi.fruitday.com' then 1 else 0 end) tag59,
                  max(case when url_host='api.95vintage.com' then 1 else 0 end) tag60,
                  max(case when url_host='ai.wcar.net.cn' then 1 else 0 end) tag61,
                  max(case when url_host='sky.vip.youku.com' then 1 else 0 end) tag62,
                  max(case when url_host='csmobile.alipay.com' then 1 else 0 end) tag63,
                  max(case when url_host='bxcloudstore.alicdn.com' then 1 else 0 end) tag64,
                  max(case when url_host='yebprod.alipay.com' then 1 else 0 end) tag65
            from user_action_tag_d 
            where  pt_days>='20190515' and pt_days<'20190620'
              and  (url_host in ('mfbizweb.19ego.cn','api.mgzf.com','ali.enmonster.com','api.hellobike.com','h5.ele.me','pages.tmall.com','h5.vip.youku.com','mps.amap.com','mtop.damai.cn','apis.didapinche.com',
                        'fragment.tmall.com','s.click.tmall.com','s.click.taobao.com','magear.pangku.com','aisle.amap.com','easysearchcard.chuxingyouhui.com','mcdj.qipinke.com','huaka.cmicrwx.cn','miniappweb.shuqireader.com',
                        'orders.kfc.com.cn','imgorder.kfc.com.cn','app.woaizuji.com','ubt.hellobike.com','crnetzsjk.crnet.info','imcd.jaxcx.com','www.mywhh.com','scofo.ofo.so','cfh.tianhongjijin.com.cn',
                        'apicall.id-photo-verify.com','scalc-min.renliwo.com','taxcal.renliwo.com','ghws5.zj12580.cn','api.zp315.cn','api.songzhaopian.com','m.rrzuji.com','www.neisha.cc','xcx.etong-online.com',
                        'mys4s.cn','lmf.gzluowang.com','appgw.cmp520.com','cityboxapi.fruitday.com','api.95vintage.com','ai.wcar.net.cn','sky.vip.youku.com','bxcloudstore.alicdn.com') 
                    or instr(url_host,'.zmxy.com')>0
                    or instr(url_host,'.antfortune.com')>0
                    or instr(url_host,'.alipay.com')>0
                    or instr(url_host,'.alipay-eco.com')>0
                    )
                    group by pt_days,
                          device_number,
                          hh) a
    group by  pt_days;


-- --京东饿了么
-- select  '京东饿了么' model,
--         '日期' pt_days, 
--         'uv1_campaign页' uv1,
--         'uv2_小米天猫' uv2,
--         'uv3_七匹狼天猫' uv3,
--         'uv4_阿迪达斯' uv4,
--         'uv5_京东大域名' uv5,
--         'uv6_京东api' uv6,
--         'uv7_京东msg' uv7,
--         'uv8_京东会员' uv8,
--         'uv9_高德下载' uv9,
--         'uv10_高德启动awaken' uv10,
--         'uv11_高德-探索附近' uv11,
--         'uv12_高德登录' uv12,
--         'uv13_侃侃' uv13,
--         'uv14_贴吧' uv14,
--         'uv15_饿了么大域名' uv15,
--         'uv16_饿了么monitor' uv16,
--         'uv17_饿了么-拉取商家列表' uv17,
--         'uv18_饿了么res' uv18,
--         'uv19_跑腿pt' uv19,
--         'uv20_饿了么tb' uv20,
--         'uv21_星选好店' uv21,
--         'uv22_饿了客服' uv22,
--         'uv23_饿了么发表评论' uv23,
--         'uv24_超市-导航栏' uv24,
--         'uv25_饿了么联名卡' uv25,
--         'uv26_领会员红包' uv26,
--         'uv27_借款' uv27,
--         'uv28_城市代理申请' uv28,
--         'uv29_饿了么支付 一小时内同时出现' uv29,
--         'uv30_饿了么企业订餐' uv30,
--         'uv31_钱包' uv31,
--         'pv1_campaign页' pv1,
--         'pv2_小米天猫' pv2,
--         'pv3_七匹狼天猫' pv3,
--         'pv4_阿迪达斯' pv4,
--         'pv5_京东大域名' pv5,
--         'pv6_京东api' pv6,
--         'pv7_京东msg' pv7,
--         'pv8_京东会员' pv8,
--         'pv9_高德下载' pv9,
--         'pv10_高德启动awaken' pv10,
--         'pv11_高德-探索附近' pv11,
--         'pv12_高德登录' pv12,
--         'pv13_侃侃' pv13,
--         'pv14_贴吧' pv14,
--         'pv15_饿了么大域名' pv15,
--         'pv16_饿了么monitor' pv16,
--         'pv17_饿了么-拉取商家列表' pv17,
--         'pv18_饿了么res' pv18,
--         'pv19_跑腿pt' pv19,
--         'pv20_饿了么tb' pv20,
--         'pv21_星选好店' pv21,
--         'pv22_饿了客服' pv22,
--         'pv23_饿了么发表评论' pv23,
--         'pv24_超市-导航栏' pv24,
--         'pv25_饿了么联名卡' pv25,
--         'pv26_领会员红包' pv26,
--         'pv27_借款' pv27,
--         'pv28_城市代理申请' pv28,
--         'pv29_饿了么支付 一小时内同时出现' pv29,
--         'pv30_饿了么企业订餐' pv30,
--         'pv31_钱包' pv31
-- union all
-- select  '京东饿了么' model,
--         pt_days,
--         count(distinct(case when tag1 =1 then device_number else null end)) uv1,
--         count(distinct(case when tag2 =1 then device_number else null end)) uv2,
--         count(distinct(case when tag3 =1 then device_number else null end)) uv3,
--         count(distinct(case when tag4 =1 then device_number else null end)) uv4,
--         count(distinct(case when tag5 =1 then device_number else null end)) uv5,
--         count(distinct(case when tag6 =1 then device_number else null end)) uv6,
--         count(distinct(case when tag7 =1 then device_number else null end)) uv7,
--         count(distinct(case when tag8 =1 then device_number else null end)) uv8,
--         count(distinct(case when tag9 =1 then device_number else null end)) uv9,
--         count(distinct(case when tag10 =1 then device_number else null end)) uv10,
--         count(distinct(case when tag11 =1 then device_number else null end)) uv11,
--         count(distinct(case when tag12 =1 then device_number else null end)) uv12,
--         count(distinct(case when tag13 =1 then device_number else null end)) uv13,
--         count(distinct(case when tag14 =1 then device_number else null end)) uv14,
--         count(distinct(case when tag15 =1 then device_number else null end)) uv15,
--         count(distinct(case when tag16 =1 then device_number else null end)) uv16,
--         count(distinct(case when tag17 =1 then device_number else null end)) uv17,
--         count(distinct(case when tag18 =1 then device_number else null end)) uv18,
--         count(distinct(case when tag19 =1 then device_number else null end)) uv19,
--         count(distinct(case when tag20 =1 then device_number else null end)) uv20,
--         count(distinct(case when tag21 =1 then device_number else null end)) uv21,
--         count(distinct(case when tag22 =1 then device_number else null end)) uv22,
--         count(distinct(case when tag23 =1 then device_number else null end)) uv23,
--         count(distinct(case when tag24 =1 then device_number else null end)) uv24,
--         count(distinct(case when tag25 =1 then device_number else null end)) uv25,
--         count(distinct(case when tag26 =1 then device_number else null end)) uv26,
--         count(distinct(case when tag27 =1 then device_number else null end)) uv27,
--         count(distinct(case when tag28 =1 then device_number else null end)) uv28,
--         count(distinct(case when tag29 =1 and tag30=1 and tag31=1 then device_number else null end)) uv29,
--         count(distinct(case when tag32 =1 then device_number else null end)) uv30,
--         count(distinct(case when tag33 =1 then device_number else null end)) uv31, 
--         sum(case when tag1 =1 then 1 else 0 end) pv1,
--         sum(case when tag2 =1 then 1 else 0 end) pv2,
--         sum(case when tag3 =1 then 1 else 0 end) pv3,
--         sum(case when tag4 =1 then 1 else 0 end) pv4,
--         sum(case when tag5 =1 then 1 else 0 end) pv5,
--         sum(case when tag6 =1 then 1 else 0 end) pv6,
--         sum(case when tag7 =1 then 1 else 0 end) pv7,
--         sum(case when tag8 =1 then 1 else 0 end) pv8,
--         sum(case when tag9 =1 then 1 else 0 end) pv9,
--         sum(case when tag10 =1 then 1 else 0 end) pv10,
--         sum(case when tag11 =1 then 1 else 0 end) pv11,
--         sum(case when tag12 =1 then 1 else 0 end) pv12,
--         sum(case when tag13 =1 then 1 else 0 end) pv13,
--         sum(case when tag14 =1 then 1 else 0 end) pv14,
--         sum(case when tag15 =1 then 1 else 0 end) pv15,
--         sum(case when tag16 =1 then 1 else 0 end) pv16,
--         sum(case when tag17 =1 then 1 else 0 end) pv17,
--         sum(case when tag18 =1 then 1 else 0 end) pv18,
--         sum(case when tag19 =1 then 1 else 0 end) pv19,
--         sum(case when tag20 =1 then 1 else 0 end) pv20,
--         sum(case when tag21 =1 then 1 else 0 end) pv21,
--         sum(case when tag22 =1 then 1 else 0 end) pv22,
--         sum(case when tag23 =1 then 1 else 0 end) pv23,
--         sum(case when tag24 =1 then 1 else 0 end) pv24,
--         sum(case when tag25 =1 then 1 else 0 end) pv25,
--         sum(case when tag26 =1 then 1 else 0 end) pv26,
--         sum(case when tag27 =1 then 1 else 0 end) pv27,
--         sum(case when tag28 =1 then 1 else 0 end) pv28,
--         sum(case when tag29 =1 and tag30=1 and tag31=1 then 1 else 0 end) pv29,
--         sum(case when tag32 =1 then 1 else 0 end) pv30,
--         sum(case when tag33 =1 then 1 else 0 end) pv31
--      from 
--         (select pt_days,
--                 device_number,
--                 hh,
--                 max(case when url_host='campaigncdn.m.taobao.com' then 1 else 0 end) tag1,
--                 max(case when url_host='xiaomi.tmall.com' then 1 else 0 end) tag2,
--                 max(case when url_host='septwolvesxb.tmall.com' then 1 else 0 end) tag3,
--                 max(case when url_host='adidas.tmall.com' then 1 else 0 end) tag4,
--                 max(case when instr(url_host,'.m.jd.com')>0  then 1 else 0 end) tag5,
--                 max(case when url_host='api.m.jd.com' then 1 else 0 end) tag6,
--                 max(case when url_host='msg.m.jd.com' then 1 else 0 end) tag7,
--                 max(case when url_host='plus.m.jd.com' then 1 else 0 end) tag8,
--                 max(case when url_host='free-mapdownload.autonavi.com' then 1 else 0 end) tag9,
--                 max(case when url_host='awaken.amap.com' then 1 else 0 end) tag10,
--                 max(case when url_host='free-store.is.autonavi.com' or url_host='m5.amap.com' then 1 else 0 end) tag11,
--                 max(case when url_host='passport.amap.com' then 1 else 0 end) tag12,
--                 max(case when url_host in ('t10.baidu.com','t11.baidu.com','t12.baidu.com') then 1 else 0 end) tag13,
--                 max(case when url_host in ('tb.himg.baidu.com','c.tieba.baidu.com') then 1 else 0 end) tag14,
--                 max(case when instr(url_host,'.ele.me')>0  then 1 else 0 end) tag15,
--                 max(case when url_host='app-monitor.ele.me' then 1 else 0 end) tag16,
--                 max(case when url_host='cube.elemecdn.com' then 1 else 0 end) tag17,
--                 max(case when url_host='restapi.ele.me' then 1 else 0 end) tag18,
--                 max(case when url_host='pt.ele.me' then 1 else 0 end) tag19,
--                 max(case when url_host='tb.ele.me' then 1 else 0 end) tag20,
--                 max(case when url_host='chosen.ele.me' then 1 else 0 end) tag21,
--                 max(case when url_host='help.ele.me' then 1 else 0 end) tag22,
--                 max(case when url_host='onepiece.faas.ele.me' then 1 else 0 end) tag23,
--                 max(case when url_host='newretail.ele.me' then 1 else 0 end) tag24,
--                 max(case when url_host='cobrand-card.faas.ele.me' then 1 else 0 end) tag25,
--                 max(case when url_host='air.tb.ele.me' then 1 else 0 end) tag26,
--                 max(case when url_host='loan-supermarket.faas.ele.me' then 1 else 0 end) tag27,
--                 max(case when url_host='daili-recruit.faas.ele.me' then 1 else 0 end) tag28,
--                 max(case when url_host='cube.elemecdn.com' then 1 else 0 end) tag29,
--                 max(case when url_host='mobile-pubt.ele.me' then 1 else 0 end) tag30,
--                 max(case when url_host='mdap.alipay.com' then 1 else 0 end) tag31,
--                 max(case when url_host='entu.ele.me' then 1 else 0 end) tag32,
--                 max(case when url_host='wallet.faas.ele.me' then 1 else 0 end) tag33
--         from user_action_tag_d 
--         where  pt_days>='20190515' and pt_days<'20190620'
--          and   (url_host in ('campaigncdn.m.taobao.com','xiaomi.tmall.com','septwolvesxb.tmall.com','adidas.tmall.com','free-mapdownload.autonavi.com','awaken.amap.com',
--                 'free-store.is.autonavi.com','m5.amap.com','passport.amap.com','t10.baidu.com','t11.baidu.com','t12.baidu.com','tb.himg.baidu.com','c.tieba.baidu.com',
--                 'cube.elemecdn.com','cube.elemecdn.com','mobilegw.alipay.com','mdap.alipay.com')
--                 or instr(url_host,'.m.jd.com')>0 
--                 or instr(url_host,'.ele.me')>0 )
--         group by pt_days,
--                 device_number,
--                 hh) a
--   group by pt_days;




--西瓜各个模块
select  '西瓜各个模块' model,
        '日期' pt_days,
        'uv_西瓜全量启动' uv1,
        'uv_西瓜未加密点击+拉取' uv2,
        'uv_西瓜未加密点击' uv3,
        'uv_西瓜搜索' uv4,
        'uv_西瓜小视频hotsoon' uv5,
        'uv_西瓜小视频tt' uv6,
        'uv_西瓜直播' uv7,
        'uv_西瓜推荐页卡' uv8,
        'uv_西瓜关注页卡' uv9,
        'uv_西瓜影视页卡' uv10,
        'uv_西瓜游戏页卡' uv11,
        'uv_西瓜社会页卡' uv12,
        'uv_西瓜NBA页卡' uv13,
        'uv_西瓜音乐页卡' uv14,
        'uv_西瓜综艺页卡' uv15,
        'uv_西瓜农人页卡' uv16,
        'uv_西瓜美食页卡' uv17,
        'uv_西瓜宠物页卡' uv18,
        'uv_西瓜体育页卡' uv19,
        'uv_西瓜懂车帝页卡' uv20,
        'pv_西瓜全量启动' pv1,
        'pv_西瓜未加密点击+拉取' pv2,
        'pv_西瓜未加密点击' pv3,
        'pv_西瓜搜索' pv4,
        'pv_西瓜小视频hotsoon' pv5,
        'pv_西瓜小视频tt' pv6,
        'pv_西瓜直播' pv7,
        'pv_西瓜推荐页卡' pv8,
        'pv_西瓜关注页卡' pv9,
        'pv_西瓜影视页卡' pv10,
        'pv_西瓜游戏页卡' pv11,
        'pv_西瓜社会页卡' pv12,
        'pv_西瓜NBA页卡' pv13,
        'pv_西瓜音乐页卡' pv14,
        'pv_西瓜综艺页卡' pv15,
        'pv_西瓜农人页卡' pv16,
        'pv_西瓜美食页卡' pv17,
        'pv_西瓜宠物页卡' pv18,
        'pv_西瓜体育页卡' pv19,
        'pv_西瓜懂车帝页卡' pv20
union all 
select '西瓜各个模块' model,
        pt_days,
        count(distinct(case when tag1=1 then device_number else null end)) uv1,
        count(distinct(case when tag2=1 then device_number else null end)) uv2,
        count(distinct(case when tag3=1 then device_number else null end)) uv3,
        count(distinct(case when tag4=1 then device_number else null end)) uv4,
        count(distinct(case when tag5=1 then device_number else null end)) uv5,
        count(distinct(case when tag6=1 then device_number else null end)) uv6,
        count(distinct(case when tag7=1 then device_number else null end)) uv7,
        count(distinct(case when tag8=1 then device_number else null end)) uv8,
        count(distinct(case when tag9=1 then device_number else null end)) uv9,
        count(distinct(case when tag10=1 then device_number else null end)) uv10,
        count(distinct(case when tag11=1 then device_number else null end)) uv11,
        count(distinct(case when tag12=1 then device_number else null end)) uv12,
        count(distinct(case when tag13=1 then device_number else null end)) uv13,
        count(distinct(case when tag14=1 then device_number else null end)) uv14,
        count(distinct(case when tag15=1 then device_number else null end)) uv15,
        count(distinct(case when tag16=1 then device_number else null end)) uv16,
        count(distinct(case when tag17=1 then device_number else null end)) uv17,
        count(distinct(case when tag18=1 then device_number else null end)) uv18,
        count(distinct(case when tag19=1 then device_number else null end)) uv19,
        count(distinct(case when tag20=1 then device_number else null end)) uv20,
        sum(case when tag1=1 then 1 else 0 end)  pv1,
        sum(case when tag2=1 then 1 else 0 end)  pv2,
        sum(case when tag3=1 then 1 else 0 end)  pv3,
        sum(case when tag4=1 then 1 else 0 end)  pv4,
        sum(case when tag5=1 then 1 else 0 end)  pv5,
        sum(case when tag6=1 then 1 else 0 end)  pv6,
        sum(case when tag7=1 then 1 else 0 end)  pv7,
        sum(case when tag8=1 then 1 else 0 end)  pv8,
        sum(case when tag9=1 then 1 else 0 end)  pv9,
        sum(case when tag10=1 then 1 else 0 end)  pv10,
        sum(case when tag11=1 then 1 else 0 end)  pv11,
        sum(case when tag12=1 then 1 else 0 end)  pv12,
        sum(case when tag13=1 then 1 else 0 end)  pv13,
        sum(case when tag14=1 then 1 else 0 end)  pv14,
        sum(case when tag15=1 then 1 else 0 end)  pv15,
        sum(case when tag16=1 then 1 else 0 end)  pv16,
        sum(case when tag17=1 then 1 else 0 end)  pv17,
        sum(case when tag18=1 then 1 else 0 end)  pv18,
        sum(case when tag19=1 then 1 else 0 end)  pv19,
        sum(case when tag20=1 then 1 else 0 end)  pv20
 from   
        (select pt_days,
                device_number,
                hh,
                max(case when instr(urltag,'app_name=video_article')>0 then 1 else 0 end) tag1,
                max(case when instr(urltag,'app_name=video_article')>0 and (instr(urltag,'vapp/action')>0 or instr(urltag,'vapp/danmaku')>0  or instr(urltag,'video/app/stream')>0)  then 1 else 0 end) tag2,
                max(case when instr(urltag,'app_name=video_article')>0 and (instr(urltag,'vapp/action')>0 or instr(urltag,'vapp/danmaku')>0) then 1 else 0 end) tag3,
                max(case when instr(urltag,'app_name=video_article')>0 and instr(urltag,'keyword')>0  then 1 else 0 end) tag4,
                max(case when instr(urltag,'app_name=video_article')>0 and instr(urltag,'category=xg_hotsoon_video')>0 then 1 else 0 end) tag5,
                max(case when instr(urltag,'app_name=video_article')>0 and instr(urltag,'tt_shortvideo')>0  then 1 else 0 end) tag6,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,'category=tt_subv_live_tab')>0 then  1 else 0 end) tag7,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,'category=video_new')>0 then  1 else 0 end) tag8,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,' category=subv_user_follow')>0 then  1 else 0 end) tag9,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,' category=subv_xg_movie')>0 then  1 else 0 end) tag10,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,' category=subv_xg_game')>0 then  1 else 0 end) tag11,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,' category=subv_xg_society')>0 then  1 else 0 end) tag12,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,' category=subv_xg_nba')>0 then  1 else 0 end) tag13,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,' category=subv_xg_music')>0 then  1 else 0 end) tag14,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,' category=subv_variety')>0 then  1 else 0 end) tag15,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,' category=subv_video_agriculture')>0 then  1 else 0 end) tag16,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,' category=subv_video_food')>0 then  1 else 0 end) tag17,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,' category=subv_video_pet')>0 then  1 else 0 end) tag18,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,' category=subv_sport')>0 then  1 else 0 end) tag19,
                max(case when instr(urltag,'app_name=video_article')>0  and instr(urltag,' category=subv_car')>0 then  1 else 0 end) tag20
        from user_action_tag_d 
        where pt_days>='20190515' and pt_days<'20190620'
        and  instr(url_host,'snssdk.com')>0 
        and  instr(urltag,'app_name=video_article')>0 
        group by pt_days,
                device_number,
                hh) a
     group by pt_days;

select  '快手各个模块' model,
        '日期' pt_days,
        'uv1_启动' uv1,
        'uv2_推荐页卡' uv2,
        'uv3_同城页卡' uv3,
        'uv4_关注页卡' uv4,
        'uv5_搜索' uv5,
        'uv6_动态' uv6,
        'uv7_消息' uv7,
        'uv8_私信' uv8,
        'uv9_评论' uv9,
        'uv10_点赞' uv10,
        'uv11_分享' uv11,
        'uv12_关注' uv12,
        'uv13_上传' uv13,
        'uv14_观看直播' uv14,
        'pv1_启动' pv1,
        'pv2_推荐页卡' pv2,
        'pv3_同城页卡' pv3,
        'pv4_关注页卡' pv4,
        'pv5_搜索' pv5,
        'pv6_动态' pv6,
        'pv7_消息' pv7,
        'pv8_私信' pv8,
        'pv9_评论' pv9,
        'pv10_点赞' pv10,
        'pv11_分享' pv11,
        'pv12_关注' pv12,
        'pv13_上传' pv13,
        'pv14_观看直播' pv14        
union all
select '快手各个模块' model,
        pt_days,
        count(distinct(case when tag1=1 then device_number else null end)) uv1,
        count(distinct(case when tag2=1 then device_number else null end)) uv2,
        count(distinct(case when tag3=1 then device_number else null end)) uv3,
        count(distinct(case when tag4=1 then device_number else null end)) uv4,
        count(distinct(case when tag5=1 then device_number else null end)) uv5,
        count(distinct(case when tag6=1 then device_number else null end)) uv6,
        count(distinct(case when tag7=1 then device_number else null end)) uv7,
        count(distinct(case when tag8=1 then device_number else null end)) uv8,
        count(distinct(case when tag9=1 then device_number else null end)) uv9,
        count(distinct(case when tag10=1 then device_number else null end)) uv10,
        count(distinct(case when tag11=1 then device_number else null end)) uv11,
        count(distinct(case when tag12=1 then device_number else null end)) uv12,
        count(distinct(case when tag13=1 then device_number else null end)) uv13,
        count(distinct(case when tag14=1 then device_number else null end)) uv14,    
        sum(case when tag1=1 then 1 else 0 end)  pv1,
        sum(case when tag2=1 then 1 else 0 end)  pv2,
        sum(case when tag3=1 then 1 else 0 end)  pv3,
        sum(case when tag4=1 then 1 else 0 end)  pv4,
        sum(case when tag5=1 then 1 else 0 end)  pv5,
        sum(case when tag6=1 then 1 else 0 end)  pv6,
        sum(case when tag7=1 then 1 else 0 end)  pv7,
        sum(case when tag8=1 then 1 else 0 end)  pv8,
        sum(case when tag9=1 then 1 else 0 end)  pv9,
        sum(case when tag10=1 then 1 else 0 end)  pv10,
        sum(case when tag11=1 then 1 else 0 end)  pv11,
        sum(case when tag12=1 then 1 else 0 end)  pv12,
        sum(case when tag13=1 then 1 else 0 end)  pv13,
        sum(case when tag14=1 then 1 else 0 end)  pv14
from 
        (select pt_days,
                hh,
                device_number,
                max(case when url_host='api.gifshow.com' then 1 else 0 end) tag1,	
                max(case when url_host='api.gifshow.com' and instr(urltag,'feed/hot')>0 then 1 else 0 end) tag2,
                max(case when url_host='api.gifshow.com' and (instr(urltag,'feed/nearby')>0  or instr(urltag,'intown')>0)  then 1 else 0 end) tag3,
                max(case when url_host='api.gifshow.com' and (instr(urltag,'myfollow')>0 or instr(urltag,'following')>0)  then 1 else 0 end) tag4,
                max(case when url_host='api.gifshow.com' and instr(urltag,'search')>0 then 1 else 0 end) tag5,
                max(case when url_host='api.gifshow.com' and instr(urltag,'news/load')>0 then 1 else 0 end) tag6,
                max(case when url_host='api.gifshow.com' and instr(urltag,'notify/load')>0 then 1 else 0 end) tag7,
                max(case when url_host='api.gifshow.com' and instr(urltag,'message')>0 then 1 else 0 end) tag8,
                max(case when url_host='api.gifshow.com' and instr(urltag,'comment/add')>0 then 1 else 0 end) tag9,
                max(case when url_host='api.gifshow.com' and instr(urltag,'photo/like')>0 then 1 else 0 end) tag10,
                max(case when url_host='api.gifshow.com' and instr(urltag,'share/sharePhoto')>0 then 1 else 0 end) tag11,
                max(case when url_host='api.gifshow.com' and instr(urltag,'relation/follow')>0 then 1 else 0 end) tag12,
                max(case when url_host='upload.gifshow.com' then 1 else 0 end) tag13,	
                max(case when url_host='live.gifshow.com' and instr(urltag,'live/startPlay')>0 then 1 else 0 end) tag14
        from user_action_tag_d 
        where  pt_days>='20190520' and pt_days<'20190620'
          and  url_host in ('api.gifshow.com','upload.gifshow.com','live.gifshow.com')
        group by pt_days,
                device_number,
                hh) a
group by pt_days;


select  '火山小视频各模块统计分析' model,
        '日期' pt_days,
        'uv_火山启动app_name' uv1,
        'uv_火山启动webcast' uv2,
        'uv_搜索' uv3,
        'uv_直播页卡' uv4,
        'uv_视频页卡' uv5,
        'uv_关注页卡' uv6,
        'uv_观看直播' uv7,
        'uv_分享链接' uv8,
        'uv_微信分享' uv9,
        'uv_微博分享' uv10,
        'uv_朋友圈分享' uv11,
        'uv_qq分享' uv12,
        'uv_qq空间分享' uv13,
        'uv_评论' uv14,
        'uv_查看他人主页' uv15,
        'uv_关注' uv16,
        'uv_发私信' uv17,
        'uv_取消关注' uv18,
        'uv_我的消息' uv19,
        'uv_钱包' uv20,
        'uv_信用卡中心' uv21,
        'uv_充值' uv22,
        'uv_支付宝充值' uv23,
        'uv_微信充值' uv24,
        'uv_发现-同城' uv25,
        'uv_发现' uv26,
        'uv_我的话题圈' uv27,
        'uv_火山K歌' uv28,
        'pv_火山启动app_name' pv1,
        'pv_火山启动webcast' pv2,
        'pv_搜索' pv3,
        'pv_直播页卡' pv4,
        'pv_视频页卡' pv5,
        'pv_关注页卡' pv6,
        'pv_观看直播' pv7,
        'pv_分享链接' pv8,
        'pv_微信分享' pv9,
        'pv_微博分享' pv10,
        'pv_朋友圈分享' pv11,
        'pv_qq分享' pv12,
        'pv_qq空间分享' pv13,
        'pv_评论' pv14,
        'pv_查看他人主页' pv15,
        'pv_关注' pv16,
        'pv_发私信' pv17,
        'pv_取消关注' pv18,
        'pv_我的消息' pv19,
        'pv_钱包' pv20,
        'pv_信用卡中心' pv21,
        'pv_充值' pv22,
        'pv_支付宝充值' pv23,
        'pv_微信充值' pv24,
        'pv_发现-同城' pv25,
        'pv_发现' pv26,
        'pv_我的话题圈' pv27,
        'pv_火山K歌' pv28
union all
select  '火山小视频各模块统计分析' model,
        pt_days,
        count(distinct(case when tag1=1 then device_number else null end)) uv1,
        count(distinct(case when tag2=1 then device_number else null end)) uv2,
        count(distinct(case when tag3=1 then device_number else null end)) uv3,
        count(distinct(case when tag4=1 then device_number else null end)) uv4,
        count(distinct(case when tag5=1 then device_number else null end)) uv5,
        count(distinct(case when tag6=1 then device_number else null end)) uv6,
        count(distinct(case when tag7=1 then device_number else null end)) uv7,
        count(distinct(case when tag8=1 then device_number else null end)) uv8,
        count(distinct(case when tag9=1 then device_number else null end)) uv9,
        count(distinct(case when tag10=1 then device_number else null end)) uv10,
        count(distinct(case when tag11=1 then device_number else null end)) uv11,
        count(distinct(case when tag12=1 then device_number else null end)) uv12,
        count(distinct(case when tag13=1 then device_number else null end)) uv13,
        count(distinct(case when tag14=1 then device_number else null end)) uv14,
        count(distinct(case when tag15=1 then device_number else null end)) uv15,
        count(distinct(case when tag16=1 then device_number else null end)) uv16,
        count(distinct(case when tag17=1 then device_number else null end)) uv17,
        count(distinct(case when tag18=1 then device_number else null end)) uv18,
        count(distinct(case when tag19=1 then device_number else null end)) uv19,
        count(distinct(case when tag20=1 then device_number else null end)) uv20,
        count(distinct(case when tag21=1 then device_number else null end)) uv21,
        count(distinct(case when tag22=1 then device_number else null end)) uv22,
        count(distinct(case when tag23=1 then device_number else null end)) uv23,
        count(distinct(case when tag24=1 then device_number else null end)) uv24,
        count(distinct(case when tag25=1 then device_number else null end)) uv25,
        count(distinct(case when tag26=1 then device_number else null end)) uv26,
        count(distinct(case when tag27=1 then device_number else null end)) uv27,
        count(distinct(case when tag28=1 then device_number else null end)) uv28,
        sum(case when tag1=1 then 1 else 0 end)  pv1,
        sum(case when tag2=1 then 1 else 0 end)  pv2,
        sum(case when tag3=1 then 1 else 0 end)  pv3,
        sum(case when tag4=1 then 1 else 0 end)  pv4,
        sum(case when tag5=1 then 1 else 0 end)  pv5,
        sum(case when tag6=1 then 1 else 0 end)  pv6,
        sum(case when tag7=1 then 1 else 0 end)  pv7,
        sum(case when tag8=1 then 1 else 0 end)  pv8,
        sum(case when tag9=1 then 1 else 0 end)  pv9,
        sum(case when tag10=1 then 1 else 0 end)  pv10,
        sum(case when tag11=1 then 1 else 0 end)  pv11,
        sum(case when tag12=1 then 1 else 0 end)  pv12,
        sum(case when tag13=1 then 1 else 0 end)  pv13,
        sum(case when tag14=1 then 1 else 0 end)  pv14,
        sum(case when tag15=1 then 1 else 0 end)  pv15,
        sum(case when tag16=1 then 1 else 0 end)  pv16,
        sum(case when tag17=1 then 1 else 0 end)  pv17,
        sum(case when tag18=1 then 1 else 0 end)  pv18,
        sum(case when tag19=1 then 1 else 0 end)  pv19,
        sum(case when tag20=1 then 1 else 0 end)  pv20,
        sum(case when tag21=1 then 1 else 0 end)  pv21,
        sum(case when tag22=1 then 1 else 0 end)  pv22,
        sum(case when tag23=1 then 1 else 0 end)  pv23,
        sum(case when tag24=1 then 1 else 0 end)  pv24,
        sum(case when tag25=1 then 1 else 0 end)  pv25,
        sum(case when tag26=1 then 1 else 0 end)  pv26,
        sum(case when tag27=1 then 1 else 0 end)  pv27,
        sum(case when tag28=1 then 1 else 0 end)  pv28
from 
        (select pt_days,
                device_number,
                hh,
                max(case when instr(url_host,'.snssdk.com')>0 and instr(urltag,'app_name=live_stream')>0 then 1 else 0 end) tag1,
                max(case when url_host='webcast.huoshan.com' then 1 else 0 end) tag2,
                max(case when instr(url_host,'.snssdk.com')>0 and instr(urltag,'hotsoon%query=')>0 then 1 else 0 end) tag3,
                max(case when url_host='webcast.huoshan.com' and instr(urltag,'type=live')>0 then 1 else 0 end) tag4,
                max(case when url_host in ('api-a.huoshan.com','hotsoon-hl.snssdk.com') and instr(urltag,'type=video')>0 then 1 else 0 end) tag5,
                max(case when url_host in ('api-a.huoshan.com','hotsoon-hl.snssdk.com') and instr(urltag,'type=follow')>0 then 1 else 0 end) tag6,
                max(case when url_host in ('quic-huoshan.snssdk.com','webcast-hl.huoshan.com') and instr(urltag,'room/enter') > 0 then 1 else 0 end) tag7,
                max(case when url_host='hotsoon.snssdk.com' and instr(urltag,'share/link_command')>0 then 1 else 0 end) tag8,
                max(case when url_host in ('hotsoon.snssdk.com','hotsoon-hl.snssdk.com') and instr(urltag,'share_way=weixin')>0 then 1 else 0 end) tag9,
                max(case when url_host in ('hotsoon.snssdk.com','hotsoon-hl.snssdk.com') and instr(urltag,'share_way=weibo')>0 then 1 else 0 end) tag10,
                max(case when url_host in ('hotsoon.snssdk.com','hotsoon-hl.snssdk.com') and instr(urltag,'share_way=weixin_timeline')>0 then 1 else 0 end) tag11,
                max(case when url_host in ('hotsoon.snssdk.com','hotsoon-hl.snssdk.com') and instr(urltag,'share_way=qq')>0 then 1 else 0 end) tag12,
                max(case when url_host in ('hotsoon.snssdk.com','hotsoon-hl.snssdk.com') and instr(urltag,'share_way=qzone')>0 then 1 else 0 end) tag13,
                max(case when url_host in ('hotsoon.snssdk.com','hotsoon-hl.snssdk.com') and instr(urltag,'comments')>0 then 1 else 0 end) tag14,
                max(case when url_host in ('hotsoon.snssdk.com','api-hl.huoshan.com') and instr(urltag,'get_profile%to_user_id')>0 then 1 else 0 end) tag15,
                max(case when url_host in ('hotsoon.snssdk.com','api-hl.huoshan.com') and instr(urltag,'_follow')>0 then 1 else 0 end) tag16,
                max(case when url_host in ('hotsoon.snssdk.com','api-hl.huoshan.com') and instr(urltag,'/ichat')>0 then 1 else 0 end) tag17,
                max(case when url_host in ('hotsoon.snssdk.com','api-hl.huoshan.com') and instr(urltag,'_unfollow')>0 then 1 else 0 end) tag18,
                max(case when url_host in ('hotsoon.snssdk.com','hotsoon-hl.snssdk.com') and instr(urltag,'get_notice')>0 then 1 else 0 end) tag19,
                max(case when url_host in ('hotsoon.snssdk.com','api-hl.huoshan.com') and instr(urltag,'wallet')>0 then 1 else 0 end) tag20,
                max(case when url_host='f-moneyloan.snssdk.com' then 1 else 0 end) tag21,
                max(case when url_host in ('hotsoon.snssdk.com','hotsoon-hl.snssdk.com') and instr(urltag,'payment_channels')>0 then 1 else 0 end) tag22,
                max(case when url_host in ('api-a.huoshan.com','api-a-hl.huoshan.com') and instr(urltag,'_buy%way=0')>0 then 1 else 0 end) tag23,
                max(case when url_host in ('api-a.huoshan.com','api-a-hl.huoshan.com') and instr(urltag,'_buy%way=1')>0 then 1 else 0 end) tag24,
                max(case when url_host in ('api-a.huoshan.com','api-a-hl.huoshan.com') and instr(urltag,'type=city')>0 then 1 else 0 end) tag25,
                max(case when url_host in ('api-a.huoshan.com','api-a-hl.huoshan.com') and instr(urltag,'type=find')>0 then 1 else 0 end) tag26,
                max(case when url_host in ('hotsoon.snssdk.com','hotsoon-hl.snssdk.com') and instr(urltag,'hashtag')>0 then 1 else 0 end) tag27,
                max(case when url_host in ('hotsoon.snssdk.com','hotsoon-hl.snssdk.com') and instr(urltag,'karaoke_hot_videos')>0 then 1 else 0 end) tag28
                from user_action_tag_d 
                where  pt_days>='20190520' and pt_days<'20190620'
                 and  (instr(url_host,'.snssdk.com')>0 or instr(url_host,'.huoshan.com')>0)
                group by pt_days,
                        device_number,
                        hh) a
group by pt_days;




--各个host的数据统计
select '白名单域名统计量' model,url_host,urltag,count(*) cnt,count(distinct device_number) dau
from user_action_tag_d where  pt_days='20190610'  group by url_host,urltag;